export enum menuPermissionEnum {
  SprintOverView = 'normal.performanceData.sprintOverview',
  SprintDetail = 'normal.performanceData.sprintDetail',
  ProjectReport = 'normal.performanceData.projectReport',
  GanttResource = 'normal.performanceData.ganttResource',
  MonthResourceReport = 'normal.performanceData.monthResourceReport',
  MonthQualityReport = 'normal.performanceData.monthQualityReport',
  ProjectTrendReport = 'normal.performanceData.projectTrendReport',
  AutoTest = 'normal.autoTest',
  AutoTestConfig = 'normal.autoTest.config',
  AutoTestHistory = 'normal.autoTest.history',
  FatCd = 'normal.fatCd',
  FatCdPipeline = 'normal.fatCd.pipeline',
  FatCdFullCoverageTrend = 'normal.fatCd.fullCoverageTrend',
  FatCdBranch = 'normal.fatCd.branchManage',
  FatCdDeployRecord = 'normal.fatCd.deployRecord',
  FatCdCoverageRecord = 'normal.fatCd.coverageRecord',
  TestTrack = 'normal.testTrack',
  TestTrackCase = 'normal.testTrack.manualCase',
  TestTrackReview = 'normal.testTrack.caseReview',
  TestTrackSmoke = 'normal.testTrack.smokePlan',
  TestTrackFunc = 'normal.testTrack.funcPlan',
  TestTrackBuriedDataOperate = 'normal.testTrack.buriedData',
  TestTrackBuriedProfileOperate = 'normal.testTrack.buriedProfile',
  Tool = 'normal.tool',
  ToolMock = 'normal.tool.mock',
  ToolFlower = 'normal.tool.flower',
  ToolPrMerge = 'normal.tool.prMerge',
  ToolJiraPrConfig = 'normal.tool.jiraPrConfig',
  ToolApprovalNotify = 'normal.tool.approvalNotify',
  DataTool = 'normal.datatool',
  Apollo = 'normal.datatool.apollo',
  ApolloIntl ='normal.datatool.apolloIntl'

}
